// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk3gQSpD-TvWbbzrySoHU46GyVYukcVeA',
    appId: '1:996803379977:web:a4ab62e603f5bfe95c09d8',
    messagingSenderId: '996803379977',
    projectId: 'scentify-8f942',
    authDomain: 'scentify-8f942.firebaseapp.com',
    storageBucket: 'scentify-8f942.appspot.com',
    measurementId: 'G-6CDY4BDEPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOuhtrcDVKdB2xj27SZF8HaK2EUuaGNf8',
    appId: '1:996803379977:android:bd56e8ddc87b97c05c09d8',
    messagingSenderId: '996803379977',
    projectId: 'scentify-8f942',
    storageBucket: 'scentify-8f942.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFlFqu43Ne01B6uSnxEpUYl3MSJkgW5tE',
    appId: '1:996803379977:ios:ed64d5d849efcf915c09d8',
    messagingSenderId: '996803379977',
    projectId: 'scentify-8f942',
    storageBucket: 'scentify-8f942.appspot.com',
    iosBundleId: 'com.example.scentify',
  );
}
